// Generates src/util/version.ts (the package version as a constant) so the
// SDK can report itself in the X-POSTGUARD-CLIENT-VERSION header.
//
// Resolution order:
//   1. process.env.PG_JS_VERSION — optional override for special builds.
//   2. package.json `version` — the real version, maintained by changesets
//      (including 0.0.0-* prereleases, which are legitimate under
//      `changeset pre` for a package that has not reached 0.0.1).
//   3. `0.0.0-dev` fallback — only if package.json is unreadable.
//
// Run as a prebuild step: node scripts/generate-version.mjs

import { readFileSync, writeFileSync } from 'fs';

function resolveVersion() {
  const fromEnv = process.env.PG_JS_VERSION?.trim();
  if (fromEnv) return fromEnv;
  try {
    const pkg = JSON.parse(readFileSync('package.json', 'utf8'));
    if (pkg.version) return pkg.version;
  } catch {
    // fall through to the dev fallback
  }
  return '0.0.0-dev';
}

const version = resolveVersion();

writeFileSync(
  'src/util/version.ts',
  `// Auto-generated by scripts/generate-version.mjs — do not edit\n` +
    `export const PG_JS_VERSION = ${JSON.stringify(version)};\n`
);

console.log(`Generated version.ts (PG_JS_VERSION=${version})`);
