// Archival direction of the envelope-compat gate (postguard-js#131).
//
// COMPATIBILITY.md: "Read support for stored artifacts is not part of this
// window. It never drops, whatever happens to the SDK version that wrote the
// bytes." So HEAD must read every envelope in the corpus, whatever produced it.
//
// The corpus is append-only and generated by scripts/generate-envelope-fixtures.mjs.
// A failure here means one of two things, and they have opposite fixes:
//   - HEAD stopped reading something it used to read -> fix HEAD;
//   - the fixture was edited -> restore it, and see check-envelope-fixtures.mjs.
//
// This class has shipped twice: pg-js >=1.1 silently stopped emitting body armor
// and broke Thunderbird detection (postguard-tb-addon#85), and the data.bin zip
// asymmetry broke the website's uuid decrypt path (#39).

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { extractCiphertext, extractUploadUuid } from '../src/email/extract.js';

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), 'fixtures', 'envelopes');

interface Fixture {
  name: string;
  description: string;
  tier: string;
  htmlBody: string;
  attachment: { name: string; contentType: string; dataBase64: string } | null;
  uploadUuid: string | null;
  expect: {
    ciphertextSha256: string | null;
    ciphertextLength: number | null;
    uploadUuid: string | null;
  };
}

function loadFixtures(): Fixture[] {
  const files = readdirSync(fixturesDir).filter((f) => f.endsWith('.json'));
  return files.map((f) => JSON.parse(readFileSync(join(fixturesDir, f), 'utf8')) as Fixture);
}

const fixtures = loadFixtures();

describe('envelope archival compatibility', () => {
  // Without this the suite would report success while asserting nothing, which
  // is the failure mode the whole gate exists to prevent. An empty directory,
  // a renamed path or a bad glob all land here.
  it('the corpus is non-empty and covers every tier', () => {
    expect(fixtures.length).toBeGreaterThan(0);
    const tiers = new Set(fixtures.map((f) => f.tier));
    expect([...tiers].sort()).toEqual(['tier1', 'tier2', 'tier3']);
  });

  describe.each(fixtures.map((f) => [f.name, f] as const))('%s', (_name, fixture) => {
    it('HEAD recovers the ciphertext this envelope carries', () => {
      const attachments = fixture.attachment
        ? [
            {
              name: fixture.attachment.name,
              data: Buffer.from(fixture.attachment.dataBase64, 'base64'),
            },
          ]
        : [];

      const recovered = extractCiphertext({ attachments });

      if (fixture.expect.ciphertextSha256 === null) {
        // Tier 3 ships no attachment on purpose — the recipient has only the
        // Cryptify link. A reader keying on the attachment alone must get null
        // here rather than throwing, and must fall through to the uuid.
        expect(recovered).toBeNull();
        return;
      }

      expect(recovered).not.toBeNull();
      expect(recovered!.length).toBe(fixture.expect.ciphertextLength);
      expect(createHash('sha256').update(recovered!).digest('hex')).toBe(
        fixture.expect.ciphertextSha256
      );
    });

    it('HEAD recovers the Cryptify uuid this envelope advertises', () => {
      expect(extractUploadUuid(fixture.htmlBody)).toBe(fixture.expect.uploadUuid);
    });

    it('the markers installed clients key on are still present', () => {
      if (fixture.attachment) {
        // Mail clients match the attachment by name and content type, not by
        // sniffing the bytes. Renaming either is a silent break for every
        // installed reader, and nothing else in the suite covers it.
        expect(fixture.attachment.name).toBe('postguard.encrypted');
        expect(fixture.attachment.contentType).toMatch(/^application\/postguard\b/);
      }
      if (fixture.expect.uploadUuid !== null) {
        // The recipient routes createEnvelope emits. extractUploadUuid keys on
        // `uuid=`, but a client that keys on the path would break silently if
        // these moved.
        expect(fixture.htmlBody).toMatch(/\/(decrypt|download)\?uuid=/);
      }
    });
  });
});
