// Archival direction of the envelope-compat gate (postguard-js#131).
//
// COMPATIBILITY.md: "Read support for stored artifacts is not part of this
// window. It never drops, whatever happens to the SDK version that wrote the
// bytes." So HEAD must read every envelope in the corpus, whatever produced it.
//
// The corpus is append-only and generated by scripts/generate-envelope-fixtures.mjs.
// A failure here means one of two things, and they have opposite fixes:
//   - HEAD stopped reading something it used to read -> fix HEAD;
//   - the fixture was edited -> restore it, and see check-envelope-fixtures.mjs.
//
// This class has shipped twice: pg-js >=1.1 silently stopped emitting body armor
// and broke Thunderbird detection (postguard-tb-addon#85), and the data.bin zip
// asymmetry broke the website's uuid decrypt path (#39).
//
// The armor half of that had no fixture until #235, so deleting
// extractArmoredCiphertext left this suite green. `legacy-armored-body.json`
// records what @e4a/pg-js 0.10.0 actually put on the wire, and every fixture now
// asserts what a reader must recover from its body — nothing, or exactly that
// block.

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  extractArmoredCiphertext,
  extractCiphertext,
  extractUploadUuid,
} from '../src/email/extract.js';

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), 'fixtures', 'envelopes');

interface Fixture {
  name: string;
  description: string;
  /** Null for a fixture that predates the tier split — currently the armored
   *  body from 0.10.0. See the corpus-shape assertion below for why that is not
   *  a hole anyone can widen. */
  tier: string | null;
  htmlBody: string;
  attachment: { name: string; contentType: string; dataBase64: string } | null;
  uploadUuid: string | null;
  expect: {
    ciphertextSha256: string | null;
    ciphertextLength: number | null;
    uploadUuid: string | null;
    /** Digest of the base64 string `extractArmoredCiphertext` must recover from
     *  `htmlBody`. Null or absent means this envelope carries no armor block and
     *  a reader must recover nothing — the four fixtures added in #131 predate
     *  the field and are that case. */
    armoredBase64Sha256?: string | null;
  };
}

function loadFixtures(): Fixture[] {
  const files = readdirSync(fixturesDir).filter((f) => f.endsWith('.json'));
  return files.map((f) => JSON.parse(readFileSync(join(fixturesDir, f), 'utf8')) as Fixture);
}

const fixtures = loadFixtures();

describe('envelope archival compatibility', () => {
  // Without this the suite would report success while asserting nothing, which
  // is the failure mode the whole gate exists to prevent. An empty directory,
  // a renamed path or a bad glob all land here.
  it('the corpus is non-empty, covers every tier, and holds an armored body', () => {
    expect(fixtures.length).toBeGreaterThan(0);

    // Tier-bearing fixtures still have to cover all three exactly. The armored
    // fixture is excluded rather than added to the expected list: adding it there
    // would mean a missing tier could be papered over by whatever else happens
    // to be in the directory.
    const tiers = new Set(fixtures.filter((f) => f.tier !== null).map((f) => f.tier));
    expect([...tiers].sort()).toEqual(['tier1', 'tier2', 'tier3']);

    // And `tier: null` is not a free pass. The only reason a fixture may lack a
    // tier is that it records a format from before tiers existed, which is the
    // armor case — so an untiered fixture must carry an armor expectation.
    for (const untiered of fixtures.filter((f) => f.tier === null)) {
      expect(typeof untiered.expect.armoredBase64Sha256).toBe('string');
    }

    // The corpus must actually hold one. Without this the armor case below takes
    // the "no armor here" branch for every fixture and the suite passes having
    // asserted nothing about extractArmoredCiphertext — the archival reader with
    // no live caller, and so the easiest one to delete (postguard-js#235).
    expect(fixtures.some((f) => typeof f.expect.armoredBase64Sha256 === 'string')).toBe(true);
  });

  describe.each(fixtures.map((f) => [f.name, f] as const))('%s', (_name, fixture) => {
    it('HEAD recovers the ciphertext this envelope carries', () => {
      // An exact-length ArrayBuffer, which is what ExtractCiphertextOptions
      // declares (src/types.ts). A bare `Buffer.from(...)` lands at a non-zero
      // byteOffset inside Node's shared 8 KiB pool for the small fixtures, so a
      // conforming reader that wraps the whole buffer would see the pool rather
      // than the fixture — and tsconfig.json's `include: ["src"]` keeps tests out
      // of `pnpm typecheck`, so the mismatch would not surface there.
      const attachments = fixture.attachment
        ? [
            {
              name: fixture.attachment.name,
              data: new Uint8Array(Buffer.from(fixture.attachment.dataBase64, 'base64')).buffer,
            },
          ]
        : [];

      const recovered = extractCiphertext({ attachments });

      if (fixture.expect.ciphertextSha256 === null) {
        // Tier 3 ships no attachment on purpose — the recipient has only the
        // Cryptify link. A reader keying on the attachment alone must get null
        // here rather than throwing, and must fall through to the uuid.
        expect(recovered).toBeNull();
        return;
      }

      expect(recovered).not.toBeNull();
      expect(recovered!.length).toBe(fixture.expect.ciphertextLength);
      expect(createHash('sha256').update(recovered!).digest('hex')).toBe(
        fixture.expect.ciphertextSha256
      );
    });

    it('HEAD recovers the in-body armor this envelope carries', () => {
      const recovered = extractArmoredCiphertext(fixture.htmlBody);
      const expected = fixture.expect.armoredBase64Sha256 ?? null;

      if (expected === null) {
        // Every envelope HEAD itself can produce. A reader must come back empty
        // rather than mistaking part of the body for a payload.
        expect(recovered).toBeNull();
        return;
      }

      expect(recovered).not.toBeNull();
      expect(createHash('sha256').update(recovered!).digest('hex')).toBe(expected);

      if (fixture.expect.ciphertextSha256 !== null) {
        // The block has to decode back to the same ciphertext the attachment
        // carries, so a reader that finds the block but mangles it — url-safe
        // substitution, dropped padding, newlines left in — fails here instead
        // of downstream in pg.open(). Guarded because an armor-only archived
        // message, with no attachment at all, is a legitimate future fixture.
        const decoded = new Uint8Array(Buffer.from(recovered!, 'base64'));
        expect(decoded.length).toBe(fixture.expect.ciphertextLength);
        expect(createHash('sha256').update(decoded).digest('hex')).toBe(
          fixture.expect.ciphertextSha256
        );
      }
    });

    it('HEAD recovers the Cryptify uuid this envelope advertises', () => {
      expect(extractUploadUuid(fixture.htmlBody)).toBe(fixture.expect.uploadUuid);
    });

    // A corpus lint, not a reader gate: every assertion here reads the fixture
    // and none calls into HEAD, so combined with the append-only guard it can
    // only ever fire on a newly added fixture. That is still worth having — it
    // rejects a fixture that does not record what a real sender emits — but the
    // forward direction is what holds HEAD to these markers. `application/postguard`
    // has no HEAD-side coverage at all: src/email/extract.ts matches on
    // `att.name === 'postguard.encrypted'` and never looks at the content type.
    it('the markers installed clients key on are recorded in this fixture', () => {
      if (fixture.attachment) {
        // Mail clients match the attachment by name and content type, not by
        // sniffing the bytes. Renaming either is a silent break for every
        // installed reader.
        expect(fixture.attachment.name).toBe('postguard.encrypted');
        expect(fixture.attachment.contentType).toMatch(/^application\/postguard\b/);
      }
      if (fixture.expect.uploadUuid !== null) {
        // The recipient routes createEnvelope emits. extractUploadUuid keys on
        // `uuid=`, but a client that keys on the path would break silently if
        // these moved.
        expect(fixture.htmlBody).toMatch(/\/(decrypt|download)\?uuid=/);
      }
    });
  });
});
