export { PostGuard } from './postguard.js';

export type {
  PostGuardConfig,
  EmailRecipient,
  EmailDomainRecipient,
  CustomPolicyRecipient,
  Recipient,
  ApiKeySign,
  YiviSign,
  SessionSign,
  SignMethod,
  SessionCallback,
  SessionRequest,
  EncryptAndUploadOptions,
  EncryptAndDeliverOptions,
  EncryptOptions,
  DecryptOptions,
  DecryptUuidOptions,
  DecryptDataOptions,
  DecryptFileResult,
  DecryptDataResult,
  SenderIdentity,
  UploadResult,
  SigningKeys,
  PolicyEntry,
  SessionStartResult,
  AttributeCon,
  BuildMimeOptions,
  CreateEnvelopeOptions,
  EnvelopeResult,
  ExtractCiphertextOptions,
} from './types.js';

export {
  PostGuardError,
  NetworkError,
  YiviNotInstalledError,
  DecryptionError,
  IdentityMismatchError,
} from './errors.js';
